### ISSUE TITLE
ValidationError: 'nperm' is a required property

### ISSUE THREAD

**Issue by cmeesters** [snakemake-workflows/rna-seq-kallisto-sleuth#57]
Hi,

upon running `snakemake --dag` on the workflow (version 2.3.2) I got:

```
WorkflowError in line 8 of /home/cm/Downloads/rna-seq-kallisto-sleuth-2.3.2/workflow/rules/common.smk:
Error validating config file.
ValidationError: 'nperm' is a required property
```
`nperm` however, is not part of the current config file at the time of writing, nor explained. It is, however, part of the schema file (`schemas/config.schema.yam`) and the report rst file. Perhaps the parameter should be considered in the template `config.yaml`, too?

Best regards
Christian

**Comment by johanneskoester** [comment]
Will have a look tomorrow!

**Comment by cmeesters** [comment]
Actually, I could plot (hence the workflow would run) with just

```
...
  fgsea:
    # tool is only run if set to `true`
    activate: false
    # if activated, you need to provide a GMT file with gene sets of interest
    gene_sets_file: "resources/gene_sets/dummy.gmt"
    fdr_gene_set: 0.05
    eps: 0.0
    nperm: 2
  spia:
  ....
  ``` 
  , where '2' is here just an arbitrary number for plotting the dag. 
  
  HTH
