### ISSUE TITLE
can base_level be multiple if has many groups? 

### ISSUE THREAD

**Issue by whiteorchid** [snakemake-workflows/rna-seq-kallisto-sleuth#66]
Dear. author,

Thanks a lot for the great tools!

May I know if it's possible to designate the **base_level** to multiple values or only one? If have multiple groups/comparisons, need to run separately (separate the units file and the sample file)?

Thank you very much!

```
diffexp:
  # samples to exclude (e.g. outliers due to technical problems)
  exclude:
  # model for sleuth differential expression analysis
  models:
    model_X:
      full: ~condition + batch
      reduced: ~batch
      # Binary valued covariate that shall be used for fold change/effect size
      # based downstream analyses.
      primary_variable: condition
      # base level of the primary variable (will be considered as denominator
      # in the fold change/effect size estimation).
      **base_level**: untreated
  # significance level to use for volcano, ma- and qq-plots
```
